name: CI

on:
  push:
    branches: [ production ]
    paths-ignore:
      - 'README.md'
      - 'helm-charts/**/README.md'
      - 'LICENSE'
  pull_request:
    branches: [ production ]
    paths-ignore:
      - 'README.md'
      - 'helm-charts/**/README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::6})

      - name: Build the tagged Docker image
        run: cd php-sample-app && docker build . --file Dockerfile --tag g3rhard/php-sample-app:${{steps.vars.outputs.tag}}

      - name: Push the tagged Docker image
        run: docker push g3rhard/php-sample-app:${{steps.vars.outputs.tag}}

      - name: Build the latest Docker image
        run: cd php-sample-app && docker build . --file Dockerfile --tag g3rhard/php-sample-app:latest

      - name: Push the latest Docker image
        run: docker push g3rhard/php-sample-app:latest

    - name: Send Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        title: "${{ github.repository }}: ${{ github.workflow }}"
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
