---
name: Snyk Container

on:
  push:
    branches: [ production ]
    paths-ignore:
      - 'README.md'
      - 'helm-charts/**/README.md'
      - 'LICENSE'
  pull_request:
    branches: [ production ]
    paths-ignore:
      - 'README.md'
      - 'helm-charts/**/README.md'
      - 'LICENSE'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build a Docker image
      run: cd php-sample-app && docker build . --file Dockerfile --tag g3rhard/php-sample-app

    - name: Run Snyk to check Docker image for vulnerabilities

      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: g3rhard/php-sample-app
        args: --file=php-sample-app/Dockerfile

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
